### PR TITLE
corrected url to include the api_key and point to the right api

### PR DESCRIPTION
**Pull request by Hesslon**
Hi Nate,

i couldn't get your implementation to work with InfusionSoft and found out that the url to their API seemed to be wrong. Could you check that and then maybe merge that back?

Thanks for your work, Ben.

### CODE REVIEW

**Comment by nateleavitt** [comment]
This is interesting.. I'll have to look into this. I know there are implementations that are using the url that doesn't seem to work for you.

**Comment by sevenseacat** [comment]
Both the REST and XMLRPC docs make mention of this, eg. https://developer.infusionsoft.com/docs/xml-rpc/

> All requests except authentication requests made to the Infusionsoft XML-RPC API will be an HTTP POST to https://api.infusionsoft.com/crm/xmlrpc/v1?access_token=123abc, and all requests made after authenticating with OAuth 2.0 must have an access token appended as the access_token query parameter in order to authenticate the request.

**Comment by sevenseacat** [comment]
That being said, with this patch I kept getting 302 redirects to log in when trying to access the API, and with the original code it works fine.

**Comment by nateleavitt** [comment]
I think I should probably add some changes in this project for the new OAuth flow.
https://github.com/nateleavitt/infusionsoft/issues/52

**Comment by nateleavitt** [comment]
I'm going to close this and refer to the OAuth 2 issue

#52

**Pull request closed without merging**
